language: vim

before_script: |
  git clone https://github.com/junegunn/vader.vim.git

script: |
  for filename in ./test/*; do
    echo "Testing filename " $filename
  vim -Nu <(cat << VIMRC
  filetype off
  set rtp+=./vader.vim/
  set rtp+=.
  set rtp+=after
  filetype plugin indent on
  syntax enable
  VIMRC) -c "+Vader! $filename" > /dev/null
  done

notifications:
    email:
        on_failure: change
        on_success: change
